version: "3"
services:
  # TODO: fix api server
  # api:
  #   container_name: nestjs_templte_api
  #   restart: always
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
volumes:
  mysql:
    driver: local
